name: Build, Push Docker Image, and Deploy CDK

on:
  push:
    branches:
      - master

jobs:
  # Job 1: Build, Push Docker Image to ECR, CDK Diff
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 905418307151.dkr.ecr.us-east-1.amazonaws.com

      # Build Docker Image
      - name: Build Docker Image
        run: |
          cd ml-code
          docker build -t 905418307151.dkr.ecr.us-east-1.amazonaws.com/mlopsinfrastack-ecrrepository4d7b3ee1-mhonmkqlgdt6:${{ github.run_number }} .

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push 905418307151.dkr.ecr.us-east-1.amazonaws.com/mlopsinfrastack-ecrrepository4d7b3ee1-mhonmkqlgdt6:${{ github.run_number }}

      # CDK Diff
      - name: CDK Diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          cd ../ mlops-infra
          npm install -g aws-cdk
          npm install
          cdk diff --context buildNumber=${{ github.run_number }}

  # Job 2: Deploy and train model
  cdk-deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment:
      name: Deploy and Train Model
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # CDK Deploy
      - name: CDK Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          cd mlops-infra
          npm install -g aws-cdk
          npm install
          cdk deploy --require-approval never --context buildNumber=${{ github.run_number }}
